// https://api.github.com/users/cgefx

export default {
  login: 'cgefx',
  id: 45520511,
  node_id: 'MDQ6VXNlcjQ1NTIwNTEx',
  avatar_url: 'https://avatars1.githubusercontent.com/u/45520511?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/cgefx',
  html_url: 'https://github.com/cgefx',
  followers_url: 'https://api.github.com/users/cgefx/followers',
  following_url: 'https://api.github.com/users/cgefx/following{/other_user}',
  gists_url: 'https://api.github.com/users/cgefx/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/cgefx/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/cgefx/subscriptions',
  organizations_url: 'https://api.github.com/users/cgefx/orgs',
  repos_url: 'https://api.github.com/users/cgefx/repos',
  events_url: 'https://api.github.com/users/cgefx/events{/privacy}',
  received_events_url: 'https://api.github.com/users/cgefx/received_events',
  type: 'User',
  site_admin: false,
  name: 'Colin A. Gibson',
  company: null,
  blog: '',
  location: 'Los Angeles, CA',
  email: null,
  hireable: null,
  bio: null,
  public_repos: 10,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: '2018-12-01T19:05:39Z',
  updated_at: '2020-04-23T21:33:20Z',
}
